Spotify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spotifyclone.urls')),


]
urlpatterns += staticfiles_urlpatterns()

spotifyclone/models.py
from django.db import models
from .validators import validate_is_audio
from .helper import get_audio_length
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class Song(models.Model):
    title = models.TextField()
    artist = models.TextField()
    image = models.ImageField()
    audio_file = models.FileField(blank=True, null=True)
    audio_link = models.CharField(max_length=200, blank=True, null=True)
    duration = models.CharField(max_length=20)
    paginate_by = 2

    def __str__(self):
        return self.title


class Music(models.Model):
    title = models.CharField(max_length=500)
    artiste = models.CharField(max_length=500)
    album = models.ForeignKey('Album', on_delete=models.SET_NULL, null=True, blank=True)
    time_length = models.DecimalField(max_digits=20, decimal_places=2, blank=True)
    audio_file = models.FileField(upload_to='musics/', validators=[validate_is_audio])
    cover_image = models.ImageField(upload_to='music_images/')

    def save(self, *args, **kwargs):
        if not self.time_length:
            # logic for getting length of audio
            audio_length = get_audio_length(self.audio_file)
            self.time_length = f'{audio_length:.2f}'

        return super().save(*args, **kwargs)

    class META:
        ordering = "id"


class Album(models.Model):
    name = models.CharField(max_length=400)


class Users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=200)
    date = models.DateField(auto_now_add=True)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

<style>
    .container {
        background-color: white;
        margin-right: auto;
        margin-left: auto;
        padding-left: 15px;
        padding-right: 15px;
    }

    body {
        font-family: Circular, Helvetica, Arial, sans-serif, IosFix;


    }

    h1 {
        font-size: 42px;
        font-weight: 900;
        letter-spacing: -0.02em;
        line-height: 2.2;
    }

    .address {
        margin-bottom: 24px;
        font-style: normal;
        line-height: 1.5;
    }
</style>
{% endblock %}

{% block body %}
<br><br><br>
<main class="container">


    <div class="row g-5 mx-4">
        <div class="col-md-8">
            <h1>About Us</h1>

            <article class="blog-post">

                <p>With Spotify, it’s easy to find the right music or podcast for every moment – on your phone, your
                    computer, your tablet and more.</p>
                <p>There are millions of tracks and episodes on Spotify. So whether you’re behind the wheel, working
                    out, partying or relaxing, the right music or podcast is always at your fingertips. Choose what you
                    want to listen to, or let Spotify surprise you.</p>
                <p>You can also browse through the collections of friends, artists, and celebrities, or create a radio
                    station and just sit back.</p>
                <p>Soundtrack your life with Spotify. Subscribe or listen for free.</p>

                <h1 style="font-size: 28px;">Customer Service and Support</h1>
                <ol>
                    <li><a href="https://bit.ly/3kW4Zmr" style="color: #1DB954;">Help site.</a> Check out our help site
                        for answers to your questions and to learn how
                        to get the most out of Spotify and your music.</li>
                    <li><a href="https://bit.ly/3yfBXlq" style="color: #1DB954;">Community.</a> Get fast support from
                        expert Spotify users. If there isn't already an
                        answer there to your question, post it and someone will quickly answer. You can also suggest and
                        vote on new ideas for Spotify or simply discuss music with other fans.</li>
                    <li> <a href="https://bit.ly/3zyTgP0" style="color: #1DB954;">Contact us.</a> Contact our Customer
                        Support if you don't find a solution on our
                        support site or Community.</li>
                    <li> <a href="https://twitter.com/SpotifyCares" style="color: #1DB954;">@SpotifyCares.</a> Feeling
                        sociable? Simply tweet the team and they'll do all they
                        can to help.</li>
                </ol>
                <blockquote class="blockquote">
                    <h1 style="font-size: 32px;">Or pick a topic:</h1>
                </blockquote>
                <ul>
                    <li>Advertising on Spotify? <a href="https://bit.ly/3iHnKaG" style="color: #1DB954;">Advertisers
                            section</a></li>
                    <li>Press query? <a href="https://bit.ly/3i2axdq" style="color: #1DB954;">Press section</a></li>
                    <li>Applying for a job?<a href="https://bit.ly/3eOMBZ2" style="color: #1DB954;">Jobs section</a>
                    </li>
                </ul>
                <p>Spotify USA, Inc. provides the Spotify service to users in the United States. Spotify AB provides the
                    Spotify service to users in all other markets.</p>
            </article>

        </div>


        <div class="col-md-4">
            <br><br><br><br><br><br>
            <h1 style="font-size: 28px;">Spotify HQ</h1>
            <address class="office">
                <strong>Spotify USA Inc</strong><br>
                4 World Trade Center<br>
                150 Greenwich Street, 62nd Floor<br>
                New York, NY 10007<br>
                USA<br>
                office@spotify.com
            </address>
            <article class="blog-post">
                <h1 style="font-size: 28px;">Spotify around the world</h1>
                <div class="offices-list-container">
                    <div class="row">

                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Belgium</strong><br>
                                Square de Meeus 37<br>
                                4th floor<br>
                                1000 Brussels<br>
                                Belgium<br>
                                office@spotify.com
                            </address>

                        </div>


                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify GmbH</strong><br>
                                Unter den Linden 10<br>
                                10117 Berlin<br>
                                Germany<br>
                                office@spotify.com
                            </address>

                        </div>

                    </div>
                    <div class="row">

                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Canada Inc.</strong><br>
                                220 Adelaide Street West<br>
                                M5H 1W7 Toronto Ontario<br>
                                Canada<br>
                                office@spotify.com
                            </address>

                        </div>


                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Denmark ApS</strong><br>
                                Vestergade 27, 1 th<br>
                                1456 København K<br>
                                Denmark<br>
                                office@spotify.com
                            </address>

                        </div>

                    </div>
                    <div class="row">

                        <div class="col-sm-6">
                            <address class="office">
                                <strong>SPOTIFY SPAIN SL</strong><br>
                                Paseo de Recoletos, 7-9<br>
                                28004 Madrid<br>
                                Spain<br>
                                office@spotify.com
                            </address>

                        </div>


                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Finland Oy</strong><br>
                                Merimiehenkatu 36 D<br>
                                FI-00150 Helsinki<br>
                                Finland<br>
                                office@spotify.com
                            </address>

                        </div>

                    </div>
                    <div class="row">

                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify France SAS</strong><br>
                                48 Rue la Bruyère<br>
                                75009<br>
                                Paris<br>
                                France<br>
                                office@spotify.com
                            </address>

                        </div>


                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify India LLP</strong><br>
                                Regus 5th &amp; 6th Floor Mafatlal House (“Building”) H.T.Parekh Marg, Backbay
                                Reclamation<br>
                                Mumbai 400020<br>
                                India<br>
                                office@spotify.com
                            </address>

                        </div>

                    </div>
                    <div class="row">

                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Italy S.r.l.</strong><br>
                                c/o Fintech District<br>
                                Via Filippo Sassetti 32<br>
                                20124 Milano<br>
                                Italy<br>
                                office@spotify.com
                            </address>

                        </div>


                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Netherlands</strong><br>
                                Singel 540 3h<br>
                                1017AZ, Amsterdam<br>
                                Netherlands<br>
                                office@spotify.com
                            </address>

                        </div>

                    </div>
                    <div class="row">

                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Poland Sp. z o.o.</strong><br>
                                Warsaw Skylight Skylight Building, 14th floor<br>
                                c/o Regus<br>
                                Ul. Zlota 59<br>
                                00-120 Warszawa<br>
                                Poland<br>
                                office@spotify.com
                            </address>

                        </div>


                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify AB</strong><br>
                                Regeringsgatan 19<br>
                                SE-111 53 Stockholm<br>
                                Sweden<br>
                                Reg no: 556703-7485<br>
                                office@spotify.com
                            </address>

                        </div>

                    </div>
                    <div class="row">

                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Ltd</strong><br>
                                Adelphi Building<br>
                                4 Savoy Place<br>
                                London WC2N 6AT<br>
                                United Kingdom<br>
                                office@spotify.com
                            </address>

                        </div>


                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Mexico</strong><br>
                                Pedregal 24 Torre Virreyes Piso 8<br>
                                Col. Molino del Rey<br>
                                DF 11040<br>
                                Mexico<br>
                                office@spotify.com
                            </address>

                        </div>

                    </div>
                    <div class="row">

                        <div class="col-sm-6">
                            <address class="office">
                                <strong>Spotify Israel</strong><br>
                                office@spotify.com
                            </address>

                        </div>

                    </div>
                </div>
            </article>

        </div>
    </div>

</main>
<br><br><br><br><br><br><br>
{% endblock %}

templates/addPage.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Spotify Clone</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Add Song</title>
</head>

<body>
    <div>
        <a href="addPage">
            <img class="d-block mx-auto my-4" src="{% static 'img/blogo.png' %}" alt="" width="72" height="57"
                style="height: 42px; width: 139px;">
        </a>
    </div>

    <h2 class="text-center text-green-700 text-2xl font-bold mt-8 mb-10">Add A new Song</h2>
    <form action="" method="post" class="w-10/12 md:w-1/2 mx-auto mb-8" enctype="multipart/form-data"
        style="display:table;">

        {% csrf_token %}


        <div class="my-4">
            <label for="id_title" class="text-lg ">Album (Optional):</label>
            <input type="text" name="album" maxlength="500" id="id_album"
                class="block w-full p-2 outline-none border-2 border-black rounded-lg">
        </div>
        <div class="my-4">
            <label for="id_title" class="text-lg ">Title:</label>
            <input type="text" name="title" maxlength="500" required="" id="id_title"
                class="block w-full p-2 outline-none border-2 border-black rounded-lg">
        </div>
        <div class="my-4">
            <label for="id_title" class="text-lg ">Artist:</label>
            <input type="text" name="artiste" maxlength="500" required="" id="id_artiste"
                class="block w-full p-2 outline-none border-2 border-black rounded-lg">
        </div>
        <div class=" overflow-hidden flex items-center justify-center flex-col my-4">
            <div class="details-audio text-black text-base">

            </div>
            <div class="flex w-full items-center justify-center bg-grey-lighter">
                <label
                    class="w-64 flex flex-col items-center px-4 py-6 bg-white text-blue rounded-lg shadow-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue-500 hover:text-white">
                    <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path
                            d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
                    </svg>
                    <span class="mt-2 text-base leading-normal">Select a Music File</span>
                    <input type='file' accept="audio/mp3" name="audio_file" class="hidden " onchange="showname('audio')"
                        id="id_audio_file" required />
                </label>
            </div>
        </div>

        <div class=" overflow-hidden flex items-center justify-center flex-col my-4">
            <div class="details-image text-black text-base">

            </div>
            <div class="flex w-full items-center justify-center bg-grey-lighter">
                <label
                    class="w-64 flex flex-col items-center px-4 py-6 bg-white text-blue rounded-lg shadow-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue-500 hover:text-white">
                    <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path
                            d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
                    </svg>
                    <span class="mt-2 text-base leading-normal">Select a Music Cover Image</span>
                    <input type='file' accept="image/*" name="cover_image" class="hidden cover_image"
                        onchange="showname('image')" id="id_cover_image" required />

                </label>

            </div><br>
            <button class="bg-black p-4 text-white text-center " style="
    margin-left: 0%;
    border-radius: 42px;
    color: black;
    padding: 1% 2%;
    background: aqua;
    width: 150px;
">
                Submit
            </button>
        </div>
    </form>

    <script>
        function showname(type) {
            if (type == 'audio') {

                var name = document.getElementById('id_audio_file');
            } else {
                var name = document.getElementById('id_cover_image');

            }
            const file_name = name.files.item(0).name
            document.querySelector(`.details-${type}`).textContent = `${file_name}`
        };
    </script>
</body>

</html>

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Listening is everything - Spotify</title>
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



    {% block css %}

    {% endblock %}

</head>

<body>
    <!-- Start Header Section -->
    <div class="header">
        <a href="/" class="logo"><img id="hd" src="{% static 'img/logo.png' %}" alt=""></a>
        <div class="header-right"></div>
        <a href="login">Log in</a>
        <a href="signup">Sign up</a>
        <a href="">|</a>
        <a href="https://www.spotify.com/us/download/windows/">Download</a>
        <a href="https://bit.ly/3y5bbfA">Support</a>
        <a href="https://www.spotify.com/us/premium/">Premium</a>
    </div>
    <!-- End Header Section -->
    {% block body %}


    {% endblock %}
    <!-- Start Footer Section -->
    <footer>
        <div class="footer">
            <div class="contain">

                <div class="col">
                    <h1>Company</h1>
                    <a href="/" class="logo"><img id="foot-img" src="{% static 'img/logo.png' %}" alt=""></a>
                    <ul>
                        <a href="/about" style="text-decoration: none;">
                            <li>About</li>
                        </a>
                        <a href="https://bit.ly/3BCVa2H" style="text-decoration: none;">
                            <li>Jobs</li>
                        </a>
                        <li>For the Record</li>
                    </ul>
                </div>
                <div class="col">
                    <h1>Communities</h1>
                    <ul>
                        <a href="https://bit.ly/36Ywnbk" style="text-decoration: none;">
                            <li>For Artists</li>
                        </a>
                        <a href="https://spoti.fi/3eTJi2x" style="text-decoration: none;">
                            <li>Developers</li>
                        </a>
                        <a href="https://bit.ly/3iCc5d6" style="text-decoration: none;">
                            <li>Advertising</li>
                        </a>
                        <a href="https://bit.ly/3rAT5jo" style="text-decoration: none;">
                            <li>Investors</li>
                        </a>
                        <a href="https://bit.ly/3i1zFRp" style="text-decoration: none;">
                            <li>Vendors</li>
                        </a>
                    </ul>
                </div>
                <div class="col">
                    <h1>Useful Links</h1>
                    <ul>
                        <a href="https://bit.ly/3y9wdtO" style="text-decoration: none;">
                            <li>Support</li>
                        </a>
                        <a href="home" style="text-decoration: none;">
                            <li>Web Player</li>
                        </a>
                        <a href="https://spoti.fi/3eU9f2a" style="text-decoration: none;">
                            <li>Free Mobile App</li>
                        </a>
                    </ul>
                </div>
                <div class="col-social">
                    <ul id="social-media">
                        <a href="https://www.instagram.com/spotify/" style="width: 60px;" class="fa fa-instagram"></a>
                        <a href="https://twitter.com/spotify" style="width: 60px;" class="fa fa-twitter"></a>
                        <a href="https://www.facebook.com/SpotifyIndia/?brand_redir=6243987495" style="width: 60px;" class="fa fa-facebook"></a>
                        </li>
                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="usa" style="padding: 1% 1% 0% 82%;color: grey;"><a href="#" style="
            text-decoration: none;
            color: gray;
        ">USA</a></div>
            <div style="padding: 1% 1% 0% 77%;color: grey;">© 2021 Spotify AB</div>
        </div>
    </footer>
    <!-- End Footer Section -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Email</title>
</head>
<body>
<div class="alert alert-success mt-5 mx-5" role="alert" style="text-align:center">
    <h2 style="text-align: center;">We have sent you an email!</h2>
    <hr>
    <h3 style="text-align: center"><a href="/login" style="text-decoration:none">Back To Login Page</a></h3>
</div>

</body>
</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1 style="text-align: center;"><a style="color:red">Error</a></h1>
<br>
<h2 style="text-align: center"><a href="/login" style="text-decoration:none" >Back To Home Page</a> </h2>
</body>
</html>

templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>
        Rockzz Player
    </title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelementplayer.min.css"
        rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <style>
        html,
        body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
        }

        .bg {
            height: 100%;
        }

        .bg1 {
            background: linear-gradient(to right,
                    rgba(5, 15, 85, 1) 0%,
                    rgba(35, 45, 135, 1) 10%,
                    rgba(88, 21, 132, 1) 32%,
                    rgba(145, 14, 115, 1) 50%,
                    rgba(185, 125, 1, 1) 100%);
        }
    </style>
</head>

<body>
    <div class="bg bg1">
        <div class="contain">
            <div class="container">
                <div class="music-player">
                    {% for item in page_obj %}
                    <div class="cover">
                        <img alt="" src="{{item.image.url}}" />
                    </div>
                    <div class="titre">
                        <h3>
                            {{item.artist}}
                        </h3>
                        <h1>
                            {{item.title}}
                        </h1>
                    </div>
                    <center><a
                            href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}"><i
                                class="fa fa-step-backward fa-2x"></i></a> &nbsp; &nbsp; &nbsp; <a
                            href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }} {% endif %}"><i
                                class="fa fa-step-forward fa-2x"></i></a></center>
                    <div class="lecteur">
                        <audio class="fc-media" style="width: 100%;">
                            <source
                                src="{% if item.audio_file %}{{item.audio_file.url}} {% else %} {{item.audio_link}} {% endif %}"
                                type="audio/mp3" />
                        </audio>

                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- partial -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelement-and-player.min.js">
    </script>
    <script src="{% static 'js/script.js' %}">
    </script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

<link href="{% static 'css/index.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{% block body %}
<!--Background Image-->
<div class="wrapper"><img id="bg" src="{% static 'img/bg.png' %}" alt=""></div>
<!--Background Image End-->
{% endblock %}

templates/success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Success!</title>
</head>

<body>
    <div class="alert alert-success mt-5 mx-5" role="alert" style="text-align:center">
        <h1 style="text-align: center;"><a style="color:green">Success!</a> your mail is verified</h1>
        <hr>
        <h2 style="text-align: center"><a href="/login" style="text-decoration:none">Back To Login Page</a></h2>
    </div>
</body>

</html>